version: '3.0'
services:
  api:
    build: ./api-server
    # ports:
      # - "11080:8000"
    working_dir: /app
    command: ['yarn', 'run', 'production']
    restart: always
    volumes:
      - /srv/cailab-database-v2/logs:/app/logs
    network_mode: bridge

  frontend:
    build: ./frontend
    # ports:
      # - "11180:80"
    links:
      - api
    depends_on:
      - api
    network_mode: bridge
    restart: always
    command: ['nginx', '-g', 'daemon off;']
